export const events = [
    { 
        title: 'Baile da favorita Tantrarosa | 30/12',
        subtitle: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Illum quibusdam id numquam magni harum ducimus eius.',
        slug: '',
        local: 'Tantrarosa, Garopaba',
        startDate: '30/12/2022 23:00:00',
        endDate: '01/01/2023 17:00:00',
        organizer: 'Luan Santos', 
        cattegory: 'Música',
        tag: 'Destaque',
        thumbnail: 'https://images.sympla.com.br/62ba06a9c38ed.png'
    },
    { 
        title: 'Feijoada com Pagode',
        subtitle: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Illum quibusdam id numquam magni harum ducimus eius.',
        slug: '',
        local: 'Arena Pantanal, Cuiabá',
        startDate: '14/03/2022 18:00:00',
        endDate: '14/03/2022 23:00:00',
        organizer: 'Luan Santos', 
        cattegory: 'Música',
        tag: 'Destaque',
        thumbnail: 'https://www.oab-ro.org.br/gerenciador/data/uploads/2017/07/ms-feijoada-oabro-rolim-moura.jpg'
    },
    { 
        title: 'Boiadeira Sunset',
        subtitle: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Illum quibusdam id numquam magni harum ducimus eius.',
        slug: '',
        local: 'Arena Pantanal, Cuiabá',
        startDate: '14/03/2022 18:00:00',
        endDate: '14/03/2022 23:00:00',
        organizer: 'Luan Santos', 
        cattegory: 'Música',
        tag: 'Em alta',
        thumbnail: 'https://caceresnoticias.nyc3.digitaloceanspaces.com/storage/webdisco/2022/10/16/original/70294a5c79296ea0affe510c92a645ae.jpg'
    },
    { 
        title: 'Revéillon 2023',
        subtitle: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Illum quibusdam id numquam magni harum ducimus eius.',
        slug: '',
        local: 'Arena Pantanal, Cuiabá',
        startDate: '14/03/2022 18:00:00',
        endDate: '14/03/2022 23:00:00',
        organizer: 'Luan Santos', 
        cattegory: 'Música',
        tag: 'Em alta',
        thumbnail: 'https://scontent.fppb1-1.fna.fbcdn.net/v/t39.30808-6/311286771_542712031191464_269976154960674515_n.jpg?_nc_cat=105&ccb=1-7&_nc_sid=730e14&_nc_ohc=_V83h281V3QAX9ygMBE&_nc_ht=scontent.fppb1-1.fna&oh=00_AfCMfjpR1uHa_Ki9huEZBabsibDNbaclwcnh4PMrJ3Bnew&oe=63B454E8'
    },
    { 
        title: 'Revéillon do Cerrado',
        subtitle: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Illum quibusdam id numquam magni harum ducimus eius.',
        slug: '',
        local: 'Arena Pantanal, Cuiabá',
        startDate: '14/03/2022 18:00:00',
        endDate: '14/03/2022 23:00:00',
        organizer: 'Luan Santos', 
        cattegory: 'Música',
        tag: 'Em alta',
        thumbnail: 'https://static-meuevento.s3.dualstack.us-east-1.amazonaws.com/event/2852a5e2-8d33-4340-81a5-4994a61f879d-imageWeb.jpg?1664463142653'
    },
    { 
        title: 'TRIBE BEAT REVEILLON ',
        subtitle: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Illum quibusdam id numquam magni harum ducimus eius.',
        slug: '',
        local: 'Arena Pantanal, Cuiabá',
        startDate: '14/03/2022 18:00:00',
        endDate: '14/03/2022 23:00:00',
        organizer: 'Luan Santos', 
        cattegory: 'Música',
        tag: 'Em alta',
        thumbnail: 'https://static-meuevento.s3.dualstack.us-east-1.amazonaws.com/event/ef92aadb-5f29-44a6-9f00-a2261aeeb0f6-imageWeb.jpg'
    },
    { 
        title: 'Sunset do Carrara',
        subtitle: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Illum quibusdam id numquam magni harum ducimus eius.',
        slug: '',
        local: 'Arena Pantanal, Cuiabá',
        startDate: '14/03/2022 18:00:00',
        endDate: '14/03/2022 23:00:00',
        organizer: 'Luan Santos', 
        cattegory: 'Música',
        tag: 'Em alta',
        thumbnail: 'https://static-meuevento.s3.dualstack.us-east-1.amazonaws.com/event/ccdebf4d-80a3-45c4-b11b-6297415c435f-imageWeb.jpg'
    },
    { 
        title: 'Reveillon Casa Sede',
        subtitle: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Illum quibusdam id numquam magni harum ducimus eius.',
        slug: '',
        local: 'Arena Pantanal, Cuiabá',
        startDate: '14/03/2022 18:00:00',
        endDate: '14/03/2022 23:00:00',
        organizer: 'Luan Santos', 
        cattegory: 'Música',
        tag: 'Em alta',
        thumbnail: 'https://static-meuevento.s3.dualstack.us-east-1.amazonaws.com/event/62b14b61-a960-41af-935a-5e6f6cde510f-imageWeb.jpg'
    },
    { 
        title: 'icaro e Gilmar',
        subtitle: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Illum quibusdam id numquam magni harum ducimus eius.',
        slug: '',
        local: 'Arena Pantanal, Cuiabá',
        startDate: '14/03/2022 18:00:00',
        endDate: '14/03/2022 23:00:00',
        organizer: 'Luan Santos', 
        cattegory: 'Música',
        tag: 'Em alta',
        thumbnail: 'https://static-meuevento.s3.dualstack.us-east-1.amazonaws.com/event/e95a8e55-485f-4919-bdd3-7ba0fe34e921-imageWeb.jpg'
    },
    { 
        title: 'JOELMA RONDONÓPOLIS ',
        subtitle: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Illum quibusdam id numquam magni harum ducimus eius.',
        slug: '',
        local: 'Arena Pantanal, Cuiabá',
        startDate: '14/03/2022 18:00:00',
        endDate: '14/03/2022 23:00:00',
        organizer: 'Luan Santos', 
        cattegory: 'Música',
        tag: 'Em alta',
        thumbnail: 'https://static-meuevento.s3.dualstack.us-east-1.amazonaws.com/event/b22e51d5-1739-4e03-beee-f3030ea3dc21-imageWeb.jpg'
    },
]