import Head from 'next/head';

import { GlobalStyle } from '@/styles/global';

import { SplashScreen } from '@/components/partials/SplashScreen';

export default function Home() {
  return (
    <>
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        {/* SEO Configs */}
        <title>TicMais</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="author" content="Mastercomps - Soluções em Tecnologia" />

        

        {/* Favicon Imports */}
        <link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon/favicon-16x16.png"></link>

        
      </Head>

      <GlobalStyle />
      
      <main>
        <SplashScreen />
      </main>
    </>
  )
}
