name: 'deploy'

jobs:
  setup:
    name: setup code for build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: send code to server
        uses: appleboy/scp-action@master
        with:
          username: deploy
          host: ${{ github.event.inputs.frontend_url }}
          password: ${{ github.event.inputs.deploy_password }}
          source: "."
          target: "/home/deploy/ticmais/store"

      - name: create .env file
        uses: appleboy/ssh-action@master
        with:
          username: deploy
          host: ${{ github.event.inputs.frontend_url }}
          password: ${{ github.event.inputs.deploy_password }}
          script: |
            cd /home/deploy/ticmais/web

            rm .env
            touch .env
            echo NEXT_PUBLIC_API_URL="${{ github.event.inputs.backend_url }}" >> .env
            echo PORT="${{ github.event.inputs.frontend_port }}" >> .env

  build:
    name: compile next.js + publish new version
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - uses: actions/checkout@v3
      - name: build and publish
        uses: appleboy/ssh-action@master
        with:
          username: deploy
          host: ${{ github.event.inputs.frontend_url }}
          password: ${{ github.event.inputs.deploy_password }}
          script: |
            cd /home/deploy/ticmais/web
            yarn build
            yarn start